export const POKEMON_RARITIES = [
  "Common",
  "Uncommon",
  "Rare",
  "Rare Holo",
  "Rare Holo V",
  "Rare Holo VSTAR",
  "Rare Holo VMAX",
  "Rare Holo EX",
  "Double Rare",
  "Ultra Rare",
  "Illustration Rare",
  "Special Illustration Rare",
  "Hyper Rare",
  "Secret Rare",
  "Promo",
  "Trainer Gallery",
  "Shiny Rare",
  "Shiny Ultra Rare",
  "Radiant Rare",
  "Amazing Rare",
  "Legend",
  "Prism Star",
  "ACE SPEC",
  "Rare BREAK",
  "Rare Prime",
  "Rare Shining",
  "Rare Holo GX",
  "Rare Rainbow",
  "Rare Shiny GX",
  "Rare Secret",
  "Rare Ultra",
  "Rare Shiny",
  "Promo (Black Star)",
  "Other / Error / Misc",
] as const;

export const POKEMON_LANGUAGES = ["English", "Japanese", "Other"];

// (Optional) handy type for TS
export type PokemonRarity = (typeof POKEMON_RARITIES)[number];
