interface Product {
  id: number;
  title: string;
  price: number;
  condition: "New" | "Used";
  image: string;
  url: string;
}

export const products: Product[] = [
  {
    id: 1,
    title: "Charizard VMAX",
    price: 120,
    condition: "New",
    image: "/mock_inventory.png",
    url: "/product/1",
  },
  {
    id: 2,
    title: "Pikachu Promo (McDonald's)",
    price: 15.5,
    condition: "Used",
    image: "/mock_inventory.png",
    url: "/product/2",
  },
  {
    id: 3,
    title: "Mewtwo EX",
    price: 40,
    condition: "New",
    image: "/mock_inventory.png",
    url: "/product/3",
  },
  {
    id: 4,
    title: "Snorlax V",
    price: 25,
    condition: "New",
    image: "/mock_inventory.png",
    url: "/product/4",
  },
  {
    id: 5,
    title: "Eevee GX",
    price: 30,
    condition: "Used",
    image: "/mock_inventory.png",
    url: "/product/5",
  },
  {
    id: 6,
    title: "Blastoise Holo Rare",
    price: 80,
    condition: "New",
    image: "/mock_inventory.png",
    url: "/product/6",
  },
  {
    id: 7,
    title: "Venusaur V",
    price: 55,
    condition: "Used",
    image: "/mock_inventory.png",
    url: "/product/7",
  },
  {
    id: 8,
    title: "Gyarados EX",
    price: 35,
    condition: "New",
    image: "/mock_inventory.png",
    url: "/product/8",
  },
  {
    id: 9,
    title: "Alakazam Holo",
    price: 45,
    condition: "Used",
    image: "/mock_inventory.png",
    url: "/product/9",
  },
  {
    id: 10,
    title: "Jigglypuff Promo",
    price: 12,
    condition: "New",
    image: "/mock_inventory.png",
    url: "/product/10",
  },
  {
    id: 11,
    title: "Dragonite VSTAR",
    price: 65,
    condition: "New",
    image: "/mock_inventory.png",
    url: "/product/11",
  },
  {
    id: 12,
    title: "Machamp Holo Rare",
    price: 22,
    condition: "Used",
    image: "/mock_inventory.png",
    url: "/product/12",
  },
  {
    id: 13,
    title: "Zapdos EX",
    price: 50,
    condition: "New",
    image: "/mock_inventory.png",
    url: "/product/13",
  },
  {
    id: 14,
    title: "Moltres Promo",
    price: 42,
    condition: "Used",
    image: "/mock_inventory.png",
    url: "/product/14",
  },
  {
    id: 15,
    title: "Articuno GX",
    price: 48,
    condition: "New",
    image: "/mock_inventory.png",
    url: "/product/15",
  },
  {
    id: 16,
    title: "Gengar Holo",
    price: 38,
    condition: "New",
    image: "/mock_inventory.png",
    url: "/product/16",
  },
  {
    id: 17,
    title: "Lucario VSTAR",
    price: 28,
    condition: "Used",
    image: "/mock_inventory.png",
    url: "/product/17",
  },
  {
    id: 18,
    title: "Sylveon V",
    price: 34,
    condition: "New",
    image: "/mock_inventory.png",
    url: "/product/18",
  },
  {
    id: 19,
    title: "Umbreon GX",
    price: 70,
    condition: "Used",
    image: "/mock_inventory.png",
    url: "/product/19",
  },
  {
    id: 20,
    title: "Espeon EX",
    price: 65,
    condition: "New",
    image: "/mock_inventory.png",
    url: "/product/20",
  },
];
